### ISSUE TITLE
Is it safe to use?

### ISSUE THREAD

**Issue by Bamboozul** [RXJpaw/Valorant-Companion#2]
I noticed that this tool shows the level of other players who have it hidden. Isn't this the kind of feature that gets you banned?

And btw, the UI is really nice.

**Comment by RXJpaw** [comment]
Yes. I mention the possibility of getting banned in the readme.
I cannot guarantee that the tool is safe to use, since it violates the ToS but working with it for over a year I can tell you I didn't get banned yet and neither did any of my friends.

To be as safe as possible consider building the executables yourself instead of relying on the provided installer since the only possibility of getting banned is a detected file-hash in vanguard.
