### ISSUE TITLE
Possible Trojan?

### ISSUE THREAD

**Issue by ConnorDoesDev** [RXJpaw/Valorant-Companion#4]
VirusTotal detects a Trojan.Heur!.02046823

**Comment by RXJpaw** [comment]
When submitting VirusTotal results please also include the link and information about what exactly you scanned so I can give you a better description of what happened. 

If you scanned the installer it's probably a false-positive caused by the nature of Windows.Squirrel. It's a wizard-less installer, meaning it needs no further user interaction that clicking the installer to run the installation process.

If you scanned the bundle it's not exactly a false-positive. When using the Account Switcher I use windows command lines to kill processes and start new ones. That could be detected as remote execution.

Please feel free to look through my code/dependencies and build the project yourself to make sure you're not installing a virus.
Also still send me the VirusTotal link and tell me what you scanned so I can get a better look at the situation.

**Comment by RXJpaw** [comment]
I have done some tests with the latest release myself. Only 1 of 89 vendors classify my latest release as "Malware".

VirusTotal results: [Master](https://www.virustotal.com/gui/url/062520dc471a0ea3bb5bda2ed3373b9b3b77e9923c51574f9b62375efae32cd0/detection), [Bundle](https://www.virustotal.com/gui/url/b383a522bb5ab008ff598bb881f301fdd9678fda7dafa20190ec3bdffffb298e/detection), [Installer](https://www.virustotal.com/gui/url/3902eeb83a7284408fb5c33a82818cb6ee406510d113c32b2799c416f3f0eb98/detection)

As long as BitDefender or other well known anti-virus vendors don't think my releases are malicious, there is no need to panic.
If you have further questions please re-open this issue with your VirusTotal results and state your concern in more detail.

**Comment by RXJpaw** [comment]
By pure chance I have found your test results on VirusTotal: [Valorant Companion.exe](https://www.virustotal.com/gui/file/0a8269c1dcf2e930555fd60cfb7801ec84f43904c572eaa173a1f11f38ff23d4/detection)

I suspect this is caused by the very nature of electron. But don't take my word for it. It could also be caused by my auto-updating implementation or using windows command lines.

**Comment by ConnorDoesDev** [comment]
Makes sense. 
Thanks for your throughout explanation! 
_Sorry for the assumption, lol_
_I'm very precautios when installing things from Github_
